name: CI Tests

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup
      run: npm ci
    - name: Check Code Style
      run: npm run lint
    - name: Build
      run: npm run ci-build
  
